// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SIAEV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.DB.AcademySubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_cuenta");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer")
                        .HasColumnName("periodo");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<string>("ReferenciaPago")
                        .HasColumnType("text")
                        .HasColumnName("referencia_pago");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_academy_subscription");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_academy_subscription_plan_id");

                    b.ToTable("academy_subscription", (string)null);
                });

            modelBuilder.Entity("Models.DB.AttentionArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CVE")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cve");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_attention_area");

                    b.ToTable("attention_area", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVE = "APRENDIZAJE",
                            Name = "Aprendizaje"
                        },
                        new
                        {
                            Id = 2,
                            CVE = "PSICOLOGIA",
                            Name = "Psicología"
                        },
                        new
                        {
                            Id = 3,
                            CVE = "COMUNICACION",
                            Name = "Comunicación"
                        },
                        new
                        {
                            Id = 4,
                            CVE = "TRABAJO_SOCIAL",
                            Name = "Trabajo Social"
                        });
                });

            modelBuilder.Entity("Models.DB.AttentionMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("phase");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_attention_mode");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_attention_mode_school_year_id");

                    b.HasIndex("StudentId", "SchoolYearId", "Phase", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_attention_mode_student_id_school_year_id_phase_type");

                    b.ToTable("attention_mode", (string)null);
                });

            modelBuilder.Entity("Models.DB.Disability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CVE")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cve");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_disability");

                    b.ToTable("disability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CVE = "INTELECTUAL",
                            Category = 1,
                            Name = "Discapacidad Intelectual"
                        },
                        new
                        {
                            Id = 2,
                            CVE = "MOTRIZ",
                            Category = 1,
                            Name = "Discapacidad Motriz"
                        },
                        new
                        {
                            Id = 3,
                            CVE = "SORDERA",
                            Category = 1,
                            Name = "Sordera"
                        },
                        new
                        {
                            Id = 4,
                            CVE = "HIPOACUSIA",
                            Category = 1,
                            Name = "Hipoacusia"
                        },
                        new
                        {
                            Id = 5,
                            CVE = "CEGUERA",
                            Category = 1,
                            Name = "Ceguera"
                        },
                        new
                        {
                            Id = 6,
                            CVE = "BAJA_VISION",
                            Category = 1,
                            Name = "Baja Visión"
                        },
                        new
                        {
                            Id = 7,
                            CVE = "MULTIPLE",
                            Category = 1,
                            Name = "Discapacidad Múltiple"
                        },
                        new
                        {
                            Id = 8,
                            CVE = "SORDOCEGUERA",
                            Category = 1,
                            Name = "Sordoceguera"
                        },
                        new
                        {
                            Id = 9,
                            CVE = "TEA",
                            Category = 1,
                            Name = "Trastorno del Espectro Autista"
                        },
                        new
                        {
                            Id = 10,
                            CVE = "TDAH",
                            Category = 2,
                            Name = "TDAH"
                        },
                        new
                        {
                            Id = 11,
                            CVE = "APRENDIZAJE",
                            Category = 2,
                            Name = "Barreras de Aprendizaje"
                        },
                        new
                        {
                            Id = 12,
                            CVE = "COMUNICACION",
                            Category = 2,
                            Name = "Barreras de Comunicación"
                        },
                        new
                        {
                            Id = 13,
                            CVE = "CONDUCTA",
                            Category = 2,
                            Name = "Barreras de Conducta"
                        },
                        new
                        {
                            Id = 14,
                            CVE = "AS",
                            Category = 3,
                            Name = "Aptitudes Sobresalientes"
                        });
                });

            modelBuilder.Entity("Models.DB.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_education_level");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_education_level_clave");

                    b.HasIndex("Orden")
                        .IsUnique()
                        .HasDatabaseName("ix_education_level_orden");

                    b.ToTable("education_level", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "PREESCOLAR",
                            Nombre = "Preescolar",
                            Orden = (short)1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "PRIMARIA",
                            Nombre = "Primaria",
                            Orden = (short)2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Clave = "SECUNDARIA",
                            Nombre = "Secundaria",
                            Orden = (short)3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Clave = "PREPARATORIA",
                            Nombre = "Preparatoria",
                            Orden = (short)4
                        });
                });

            modelBuilder.Entity("Models.DB.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("education_level_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_grade");

                    b.HasIndex("EducationLevelId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_education_level_id_numero");

                    b.ToTable("grade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevelId = 1,
                            Nombre = "Primero",
                            Numero = (short)1
                        },
                        new
                        {
                            Id = 2,
                            EducationLevelId = 1,
                            Nombre = "Segundo",
                            Numero = (short)2
                        },
                        new
                        {
                            Id = 3,
                            EducationLevelId = 1,
                            Nombre = "Tercero",
                            Numero = (short)3
                        },
                        new
                        {
                            Id = 4,
                            EducationLevelId = 2,
                            Nombre = "Primero",
                            Numero = (short)1
                        },
                        new
                        {
                            Id = 5,
                            EducationLevelId = 2,
                            Nombre = "Segundo",
                            Numero = (short)2
                        },
                        new
                        {
                            Id = 6,
                            EducationLevelId = 2,
                            Nombre = "Tercero",
                            Numero = (short)3
                        },
                        new
                        {
                            Id = 7,
                            EducationLevelId = 2,
                            Nombre = "Cuarto",
                            Numero = (short)4
                        },
                        new
                        {
                            Id = 8,
                            EducationLevelId = 2,
                            Nombre = "Quinto",
                            Numero = (short)5
                        },
                        new
                        {
                            Id = 9,
                            EducationLevelId = 2,
                            Nombre = "Sexto",
                            Numero = (short)6
                        },
                        new
                        {
                            Id = 10,
                            EducationLevelId = 3,
                            Nombre = "Primero",
                            Numero = (short)1
                        },
                        new
                        {
                            Id = 11,
                            EducationLevelId = 3,
                            Nombre = "Segundo",
                            Numero = (short)2
                        },
                        new
                        {
                            Id = 12,
                            EducationLevelId = 3,
                            Nombre = "Tercero",
                            Numero = (short)3
                        },
                        new
                        {
                            Id = 13,
                            EducationLevelId = 4,
                            Nombre = "Primer semestre",
                            Numero = (short)1
                        },
                        new
                        {
                            Id = 14,
                            EducationLevelId = 4,
                            Nombre = "Segundo semestre",
                            Numero = (short)2
                        },
                        new
                        {
                            Id = 15,
                            EducationLevelId = 4,
                            Nombre = "Tercer semestre",
                            Numero = (short)3
                        },
                        new
                        {
                            Id = 16,
                            EducationLevelId = 4,
                            Nombre = "Cuarto semestre",
                            Numero = (short)4
                        },
                        new
                        {
                            Id = 17,
                            EducationLevelId = 4,
                            Nombre = "Quinto semestre",
                            Numero = (short)5
                        },
                        new
                        {
                            Id = 18,
                            EducationLevelId = 4,
                            Nombre = "Sexto semestre",
                            Numero = (short)6
                        });
                });

            modelBuilder.Entity("Models.DB.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_id");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_group_grade_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_group_school_year_id");

                    b.HasIndex("SchoolId", "GradeId", "Section", "SchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_school_id_grade_id_section_school_year_id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Models.DB.IndividualSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer")
                        .HasColumnName("periodo");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<string>("ReferenciaPago")
                        .HasColumnType("text")
                        .HasColumnName("referencia_pago");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_individual_subscription");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_individual_subscription_plan_id");

                    b.ToTable("individual_subscription", (string)null);
                });

            modelBuilder.Entity("Models.DB.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoR2Key")
                        .HasColumnType("text")
                        .HasColumnName("archivo_r2key");

                    b.Property<string>("ArchivoUrl")
                        .HasColumnType("text")
                        .HasColumnName("archivo_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("Folio")
                        .HasColumnType("text")
                        .HasColumnName("folio");

                    b.Property<decimal>("IVA")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("iva");

                    b.Property<string>("RFC")
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenFiscal")
                        .HasColumnType("text")
                        .HasColumnName("regimen_fiscal");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.Property<string>("UsoCFDI")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uso_cfdi");

                    b.HasKey("Id")
                        .HasName("pk_invoice");

                    b.HasIndex("Folio")
                        .IsUnique()
                        .HasDatabaseName("ix_invoice_folio");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_invoice_transaction_id");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("Models.DB.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationUrl")
                        .HasColumnType("text")
                        .HasColumnName("destination_url");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean")
                        .HasColumnName("read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_user_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Models.DB.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademySubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("academy_subscription_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_predeterminado");

                    b.Property<int?>("IndividualSubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("individual_subscription_id");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<int>("Proveedor")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor");

                    b.Property<string>("ReferenciaExt")
                        .HasColumnType("text")
                        .HasColumnName("referencia_ext");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titular")
                        .HasColumnType("text")
                        .HasColumnName("titular");

                    b.Property<string>("UltimosDigitos")
                        .HasColumnType("text")
                        .HasColumnName("ultimos_digitos");

                    b.HasKey("Id")
                        .HasName("pk_payment_method");

                    b.HasIndex("AcademySubscriptionId")
                        .HasDatabaseName("ix_payment_method_academy_subscription_id");

                    b.HasIndex("IndividualSubscriptionId")
                        .HasDatabaseName("ix_payment_method_individual_subscription_id");

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("Models.DB.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FinalSituation")
                        .HasColumnType("integer")
                        .HasColumnName("final_situation");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateOnly>("IngressDate")
                        .HasColumnType("date")
                        .HasColumnName("ingress_date");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new");

                    b.Property<bool>("IsTracking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tracking");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_registration");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_registration_group_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_registration_school_year_id");

                    b.HasIndex("StudentId", "SchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_student_id_school_year_id");

                    b.ToTable("registration", (string)null);
                });

            modelBuilder.Entity("Models.DB.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Permisos")
                        .HasColumnType("jsonb")
                        .HasColumnName("permisos");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_role_clave");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "ADMIN",
                            Nombre = "Administrador del sistema"
                        },
                        new
                        {
                            Id = 2,
                            Clave = "SUPERVISOR",
                            Nombre = "Supervisor de zona"
                        },
                        new
                        {
                            Id = 3,
                            Clave = "DIRECTOR_USAER",
                            Nombre = "Director de USAER"
                        },
                        new
                        {
                            Id = 4,
                            Clave = "ESPECIALISTA_COM",
                            Nombre = "Especialista en Comunicación"
                        },
                        new
                        {
                            Id = 5,
                            Clave = "ESPECIALISTA_PSI",
                            Nombre = "Especialista en Psicología"
                        },
                        new
                        {
                            Id = 6,
                            Clave = "ESPECIALISTA_APR",
                            Nombre = "Especialista en Aprendizaje"
                        },
                        new
                        {
                            Id = 7,
                            Clave = "TRABAJO_SOCIAL",
                            Nombre = "Trabajo Social"
                        },
                        new
                        {
                            Id = 8,
                            Clave = "DOCENTE",
                            Nombre = "Docente de grupo regular"
                        },
                        new
                        {
                            Id = 9,
                            Clave = "TUTOR",
                            Nombre = "Padre / tutor"
                        },
                        new
                        {
                            Id = 10,
                            Clave = "ALUMNO",
                            Nombre = "Alumno (autoservicio)"
                        });
                });

            modelBuilder.Entity("Models.DB.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademySubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("academy_subscription_id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CCT")
                        .HasColumnType("text")
                        .HasColumnName("cct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EducationLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("education_level_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("SchoolZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("school_zone_id");

                    b.Property<int>("Turn")
                        .HasColumnType("integer")
                        .HasColumnName("turn");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_school");

                    b.HasIndex("AcademySubscriptionId")
                        .HasDatabaseName("ix_school_academy_subscription_id");

                    b.HasIndex("CCT")
                        .IsUnique()
                        .HasDatabaseName("ix_school_cct");

                    b.HasIndex("EducationLevelId")
                        .HasDatabaseName("ix_school_education_level_id");

                    b.HasIndex("SchoolZoneId")
                        .HasDatabaseName("ix_school_school_zone_id");

                    b.ToTable("school", (string)null);
                });

            modelBuilder.Entity("Models.DB.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_school_year");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_school_year_name");

                    b.ToTable("school_year", (string)null);
                });

            modelBuilder.Entity("Models.DB.SchoolZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademySubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("academy_subscription_id");

                    b.Property<string>("CCT")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cct");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_school_zone");

                    b.HasIndex("AcademySubscriptionId")
                        .HasDatabaseName("ix_school_zone_academy_subscription_id");

                    b.HasIndex("CCT")
                        .IsUnique()
                        .HasDatabaseName("ix_school_zone_cct");

                    b.ToTable("school_zone", (string)null);
                });

            modelBuilder.Entity("Models.DB.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CURP")
                        .HasColumnType("text")
                        .HasColumnName("curp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FatherLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_last_name");

                    b.Property<string>("MotherLastName")
                        .HasColumnType("text")
                        .HasColumnName("mother_last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("CURP")
                        .IsUnique()
                        .HasDatabaseName("ix_student_curp");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_user_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Models.DB.Student", b =>
                {
                    b.HasOne("Models.DB.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.DB.StudentAttentionAreas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttentionAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("attention_area_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_attention_area");

                    b.HasIndex("AttentionAreaId")
                        .HasDatabaseName("ix_student_attention_area_attention_area_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_student_attention_area_school_year_id");

                    b.HasIndex("StudentId", "AttentionAreaId", "SchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_attention_area_student_id_attention_area_id_school_");

                    b.ToTable("student_attention_area", (string)null);
                });

            modelBuilder.Entity("Models.DB.StudentDisability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("disability_id");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("document_url");

                    b.Property<bool>("ExternalDiagnosis")
                        .HasColumnType("boolean")
                        .HasColumnName("external_diagnosis");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_disability");

                    b.HasIndex("DisabilityId")
                        .HasDatabaseName("ix_student_disability_disability_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_student_disability_school_year_id");

                    b.HasIndex("StudentId", "DisabilityId", "SchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_disability_student_id_disability_id_school_year_id");

                    b.ToTable("student_disability", (string)null);
                });

            modelBuilder.Entity("Models.DB.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("jsonb")
                        .HasColumnName("caracteristicas");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("MaxAlumnos")
                        .HasColumnType("integer")
                        .HasColumnName("max_alumnos");

                    b.Property<int?>("MaxUsuarios")
                        .HasColumnType("integer")
                        .HasColumnName("max_usuarios");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioAnual")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_anual");

                    b.Property<decimal>("PrecioMensual")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_mensual");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plan");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_plan_clave");

                    b.ToTable("subscription_plan", (string)null);
                });

            modelBuilder.Entity("Models.DB.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademySubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("academy_subscription_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("text")
                        .HasColumnName("error_mensaje");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("IndividualSubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("individual_subscription_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("ReferenciaExt")
                        .HasColumnType("text")
                        .HasColumnName("referencia_ext");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("AcademySubscriptionId")
                        .HasDatabaseName("ix_transaction_academy_subscription_id");

                    b.HasIndex("IndividualSubscriptionId")
                        .HasDatabaseName("ix_transaction_individual_subscription_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_transaction_payment_method_id");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("Models.DB.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CompleteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complete_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text")
                        .HasColumnName("parentesco");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tutor");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_tutor_student_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tutor_user_id");

                    b.ToTable("tutor", (string)null);
                });

            modelBuilder.Entity("Models.DB.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int?>("AcademySubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("academy_subscription_id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FatherLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_last_name");

                    b.Property<string>("MotherLastName")
                        .HasColumnType("text")
                        .HasColumnName("mother_last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int?>("SchoolZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("school_zone_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("AcademySubscriptionId")
                        .HasDatabaseName("ix_user_academy_subscription_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_id");

                    b.HasIndex("SchoolZoneId")
                        .HasDatabaseName("ix_user_school_zone_id");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@system.com",
                            FatherLastName = "Sistema",
                            Name = "Admin",
                            PasswordHash = "cTZfg3WXU8h6n6cVkemLpgFsbETdN1tsoL3dVM10HuM=",
                            PasswordSalt = "322JhrUxDTVzC5KijDL+FlE+Zk22My5MRBC89R8noN4=",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Models.DB.UserGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsTitular")
                        .HasColumnType("boolean")
                        .HasColumnName("es_titular");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_group");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_user_group_group_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_user_group_school_year_id");

                    b.HasIndex("UserId", "GroupId", "SchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_group_user_id_group_id_school_year_id");

                    b.ToTable("user_group", (string)null);
                });

            modelBuilder.Entity("Models.DB.UserSchools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_school");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_user_school_school_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_user_school_school_year_id");

                    b.HasIndex("UserId", "SchoolId", "SchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_school_user_id_school_id_school_year_id");

                    b.ToTable("user_school", (string)null);
                });

            modelBuilder.Entity("Models.DB.AcademySubscription", b =>
                {
                    b.HasOne("Models.DB.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academy_subscription_subscription_plan_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Models.DB.AttentionMode", b =>
                {
                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attention_mode_school_year_school_year_id");

                    b.HasOne("Models.DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attention_mode_student_student_id");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Models.DB.Grade", b =>
                {
                    b.HasOne("Models.DB.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_education_level_education_level_id");

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("Models.DB.Group", b =>
                {
                    b.HasOne("Models.DB.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_grade_grade_id");

                    b.HasOne("Models.DB.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_school_school_id");

                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_school_year_school_year_id");

                    b.Navigation("Grade");

                    b.Navigation("School");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Models.DB.IndividualSubscription", b =>
                {
                    b.HasOne("Models.DB.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_individual_subscription_subscription_plan_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Models.DB.Invoice", b =>
                {
                    b.HasOne("Models.DB.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_transaction_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Models.DB.Notification", b =>
                {
                    b.HasOne("Models.DB.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.DB.PaymentMethod", b =>
                {
                    b.HasOne("Models.DB.AcademySubscription", "AcademySubscription")
                        .WithMany()
                        .HasForeignKey("AcademySubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_method_academy_subscription_academy_subscription_id");

                    b.HasOne("Models.DB.IndividualSubscription", "IndividualSubscription")
                        .WithMany()
                        .HasForeignKey("IndividualSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_method_individual_subscription_individual_subscript");

                    b.Navigation("AcademySubscription");

                    b.Navigation("IndividualSubscription");
                });

            modelBuilder.Entity("Models.DB.Registration", b =>
                {
                    b.HasOne("Models.DB.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registration_group_group_id");

                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registration_school_year_school_year_id");

                    b.HasOne("Models.DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_student_student_id");

                    b.Navigation("Group");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Models.DB.School", b =>
                {
                    b.HasOne("Models.DB.AcademySubscription", "AcademySubscription")
                        .WithMany()
                        .HasForeignKey("AcademySubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_school_academy_subscription_academy_subscription_id");

                    b.HasOne("Models.DB.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_school_education_level_education_level_id");

                    b.HasOne("Models.DB.SchoolZone", "SchoolZone")
                        .WithMany("Schools")
                        .HasForeignKey("SchoolZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_school_school_zone_school_zone_id");

                    b.Navigation("AcademySubscription");

                    b.Navigation("EducationLevel");

                    b.Navigation("SchoolZone");
                });

            modelBuilder.Entity("Models.DB.SchoolZone", b =>
                {
                    b.HasOne("Models.DB.AcademySubscription", "AcademySubscription")
                        .WithMany()
                        .HasForeignKey("AcademySubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_school_zone_academy_subscription_academy_subscription_id");

                    b.Navigation("AcademySubscription");
                });

            modelBuilder.Entity("Models.DB.StudentAttentionAreas", b =>
                {
                    b.HasOne("Models.DB.AttentionArea", "AttentionArea")
                        .WithMany()
                        .HasForeignKey("AttentionAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_attention_area_attention_area_attention_area_id");

                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_attention_area_school_year_school_year_id");

                    b.HasOne("Models.DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_attention_area_student_student_id");

                    b.Navigation("AttentionArea");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Models.DB.StudentDisability", b =>
                {
                    b.HasOne("Models.DB.Disability", "Disability")
                        .WithMany()
                        .HasForeignKey("DisabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_disability_disability_disability_id");

                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_disability_school_year_school_year_id");

                    b.HasOne("Models.DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_disability_student_student_id");

                    b.Navigation("Disability");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Models.DB.Transaction", b =>
                {
                    b.HasOne("Models.DB.AcademySubscription", "AcademySubscription")
                        .WithMany()
                        .HasForeignKey("AcademySubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transaction_academy_subscription_academy_subscription_id");

                    b.HasOne("Models.DB.IndividualSubscription", "IndividualSubscription")
                        .WithMany()
                        .HasForeignKey("IndividualSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transaction_individual_subscription_individual_subscription");

                    b.HasOne("Models.DB.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transaction_payment_method_payment_method_id");

                    b.Navigation("AcademySubscription");

                    b.Navigation("IndividualSubscription");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Models.DB.Tutor", b =>
                {
                    b.HasOne("Models.DB.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutor_student_student_id");

                    b.HasOne("Models.DB.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tutor_user_user_id");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.DB.User", b =>
                {
                    b.HasOne("Models.DB.AcademySubscription", "AcademySubscription")
                        .WithMany()
                        .HasForeignKey("AcademySubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_academy_subscription_academy_subscription_id");

                    b.HasOne("Models.DB.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_id");

                    b.HasOne("Models.DB.SchoolZone", "SchoolZone")
                        .WithMany()
                        .HasForeignKey("SchoolZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_school_zone_school_zone_id");

                    b.Navigation("AcademySubscription");

                    b.Navigation("Role");

                    b.Navigation("SchoolZone");
                });

            modelBuilder.Entity("Models.DB.UserGroups", b =>
                {
                    b.HasOne("Models.DB.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_group_group_id");

                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_school_year_school_year_id");

                    b.HasOne("Models.DB.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_user_user_id");

                    b.Navigation("Group");

                    b.Navigation("SchoolYear");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.DB.UserSchools", b =>
                {
                    b.HasOne("Models.DB.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_school_school_school_id");

                    b.HasOne("Models.DB.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_school_school_year_school_year_id");

                    b.HasOne("Models.DB.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_school_user_user_id");

                    b.Navigation("School");

                    b.Navigation("SchoolYear");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.DB.SchoolZone", b =>
                {
                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
