namespace Models.DB;

public class Report
{
    public Guid Id { get; set; }
    public string Type { get; set; } = null!;
    public string? ParametersJson { get; set; } // JSONB
    public string? ContentJson { get; set; } // JSONB
    public string? FileUrl { get; set; }
    public string Format { get; set; } = "PDF";
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Student (optional)
    public Student? Student { get; set; }
    public Guid? StudentId { get; set; }

    // Group (optional)
    public Group? Group { get; set; }
    public Guid? GroupId { get; set; }

    // School year
    public SchoolYear SchoolYear { get; set; } = null!;
    public Guid SchoolYearId { get; set; }

    // Generated by
    public User GeneratedBy { get; set; } = null!;
    public Guid GeneratedById { get; set; }
}
